language: python
python:
  - 3.4
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
# install dependencies
install:
  - pip install .
# run tests
script:
  - ls
  - python -m unittest -s pyIMD/pyIMD/tests -t pyIMD/pyIMD/tests