language: python
matrix:
  include:
  - name: "Python 3.5 on Linux"
    dist: xenial
    python: 3.5
    env:
      - PYTHON_VERSION=3.5
      - DEPLOY_FILE="/home/travis/build/cunyap/pyIMD/dist/pyIMD_x64_unix"
      - OS_TYPE=linux
  - name: "Python 3.6 on Linux"
    python: 3.6
    env:
      - PYTHON_VERSION=3.6
      - OS_TYPE=linux
  - name: "Python 3.7 on Xenial Linux"
    python: 3.7
    dist: xenial          # required for Python >= 3.7
    sudo: true
    env:
      - PYTHON_VERSION=3.7
      - OS_TYPE=linux
  - name: "Python 3.5 on macOS"
    os: osx
    osx_image: xcode8
    language: generic       # 'language: python' is an error on Travis CI macOS
    env:
      - PYTHON_VERSION=3.5
      - DEPLOY_FILE="/Users/travis/build/cunyap/pyIMD/dist/pyIMD_x64_osx.dmg"
      - OS_TYPE=osx
  - name: "Python 3.6 on macOS"
    os: osx
    language: generic
    env:
      - PYTHON_VERSION=3.6
      - OS_TYPE=osx
  - name: "Python 3.7 on macOS"
    os: osx
    language: generic
    env:
      - PYTHON_VERSION=3.7
      - OS_TYPE=osx
before_install:
- source ./pyIMD/ci/setup_python.sh $PYTHON_VERSION $OS_TYPE
install:
- bash $TRAVIS_BUILD_DIR/pyIMD/ci/build.sh $TRAVIS_OS_NAME $PYTHON_VERSION
before_script: cd ${TRAVIS_BUILD_DIR}/pyIMD/examples
# script:
# - "if [\"$TRAVIS_OS_NAME\" = \"windows\"]; then\n  python3 -m unittest discover -s
#   $TRAVIS_BUILD_DIR/pyIMD/tests -t $TRAVIS_BUILD_DIR/pyIMD/tests\nelse \n  python
#   -m unittest discover -s $TRAVIS_BUILD_DIR/pyIMD/tests -t $TRAVIS_BUILD_DIR/pyIMD/tests\nfi
#   \n"
deploy:
  provider: releases
  api_key:
    secure: ad5sOFsBOVecCOtjhX8ZGyQ7JYZqGFtcwLOzaxudpch+IFcOkCe3q0NF1CMVPWg4OwqF3vVLUp7IUwTorfPn6WbmuaqDC3LI4dCs5jsmjXzTuYzxvRaSeGookCCsQ4+AYO5f4zoOJ/Lnq2FU99z5zG9BFzCKeQ6XeCGui9HqsElSSR2FMDlqKL5DgcJW4XMEJu6zHattxEPukyijXvrVKC76SpLMLm69XkrL0OiUiHX8SiurE+K3choFau13vsHRjhKHUzKhLRWINX0uqvITHQJ0YEhiTXyp0xPwuHJz1Cf19UwkE/z1KAosI3iLdPzKIHJnz+58Oa0CMj+6iJFX2lV0sNPkqXA3ywTvhmEUmLniwOALZBi/2YuThFiKV67gebCCkitbZyDgvuKjrbtIfrAYSUrEnMAfCvWcQaX7X0j5xE4DK1Opd94mdUXtSN+1L3qprVPsruuRfB5Csxn1+FjQvFeaWH5YIAQImGvtqBPpmE8K8Q0SIWMvQ5DLVT99n3IB4Tr71uz9VaCCdxSzEouedB6c8kNsX6/Tw0JPna+w2HAFfJ1ZeOQc8EsCgiMNGAYWKSmJPJR3v+AMXRsyF+FdhfjqpaNcl3tK/RIX4xQHtu5vlpiqCjmWcx2IOG48lP61di20K3yhlWcT9h4LMzG9or5pioWH1ppITL8BYsg=
  file: $DEPLOY_FILE
  skip_cleanup: true
  on:
    tags: true
    condition: $PYTHON_VERSION = 3.5
    repo: cunyap/pyIMD
